language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install twine;
  - pip install -e .
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
      python setup.py sdist bdist_wheel;
    fi
  - wget -O softIoc.tgz "https://drive.google.com/uc?export=download&id=0B71karoHGq-HNHkxTEw4Tkh5MDA"
  - tar zxf softIoc.tgz
  - pip install git+https://github.com/CaChannel/CaChannel.git

# The travis Python 3.5 with numpy compiled with OpenBLAS, which has the following deadlock
# https://github.com/xianyi/OpenBLAS/issues/937

script:
  - export OPENBLAS_NUM_THREADS=1
  - export EPICS_CA_AUTO_ADDR_LIST=NO
  - export EPICS_CA_ADDR_LIST=127.255.255.255
  - cd softIoc
  - export PATH=`pwd`:$PATH
  - ./softIoc -D softIoc.dbd -S -d test.db &
  - PID=$!
  - cd ..
  - py.test tests/test_context.py -sv
  - py.test tests/test_preemptive.py
  - py.test tests/test_thread.py
  - py.test tests/test_callbacks.py
  - py.test tests/test_put_types.py
  - py.test tests/test_get_dbrtypes.py
  - py.test tests/test_sg.py
  - export CACHANNEL_BACKEND=caffi
  - python -m CaChannel.CaChannel
  - kill -9 $PID

after_success:
  - if [[ ! -z "$TRAVIS_TAG" && $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
      echo [distutils]                > ~/.pypirc;
      echo index-servers = mypypi    >> ~/.pypirc;
      echo [mypypi]                  >> ~/.pypirc;
      echo repository=$PYPI_URL      >> ~/.pypirc;
      echo username=$PYPI_USER       >> ~/.pypirc;
      echo password=$PYPI_PASSWORD   >> ~/.pypirc;
      twine upload -r mypypi dist/caffi-*.tar.gz;
      twine upload -r mypypi dist/caffi-*.whl;
    fi
