language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install twine;
  - pip install -e .
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
      python setup.py sdist bdist_wheel;
    fi

script:
  - python -c "import caffi.ca"

after_success:
  - if [[ ! -z "$TRAVIS_TAG" && $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
      echo [distutils]                > ~/.pypirc;
      echo index-servers = mypypi    >> ~/.pypirc;
      echo [mypypi]                  >> ~/.pypirc;
      echo repository=$PYPI_URL      >> ~/.pypirc;
      echo username=$PYPI_USER       >> ~/.pypirc;
      echo password=$PYPI_PASSWORD   >> ~/.pypirc;
      twine upload -r mypypi dist/caffi-*.tar.gz;
      twine upload -r mypypi dist/caffi-*.whl;
    fi
