package:
  name: caffi
  version: 1.0.2

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.3
    - enum34 # [py2k]

  run:
    - python
    - cffi >=1.3
    - enum34 # [py2k]
    - epics-base

build:
  noarch: python

test:
  imports:
    - caffi

about:
  home: https://github.com/CaChannel/caffi/
  license: BSD License
  summary: 'Channel Access Foreign Function Interface'

